### ISSUE TITLE
Include R with the Extension

### ISSUE THREAD

**Issue by EagleoutIce** [Code-Inspect/vscode-flowr#5]
If R is not installed on the host system we want to at least inform the user and allow to download/setup R (maybe even as part of the package!).

**Comment by Ellpeck** [comment]
Something like this (from the CodeQL extension) would be ideal for this extension installing R automatically

![image](https://github.com/Code-Inspect/vscode-flowr/assets/5741138/d70db712-0ba8-4331-aaae-5fb46d63300c)

**Comment by Ellpeck** [comment]
there's no non-installer version of R for windows and i want to cry

**Comment by Ellpeck** [comment]
It turns out that including R with the extension isn't really feasible, since most versions don't have a direct downloadable binary, and the windows version only has an inno installer that we'd have to execute manually. 

It seems that this is the reason other R-related stuff doesn't ship with R, but makes you install it manually. Oh well.
